# **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [2]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [3]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data’: File exists

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [4]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.9 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 5.6 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 6.4 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [5]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Step 1: Search for Traget Protein

## **Target Identification (NKX3-1)**
Search ChEMBL for the NKX3-1 target and select the most relevant entry.

In [7]:
target = new_client.target
target_query = target.search("NKX3-1")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,B2 bradykinin receptor,8.0,False,CHEMBL3157,"[{'accession': 'P30411', 'component_descriptio...",SINGLE PROTEIN,9606.0
1,[],Homo sapiens,Bone morphogenetic protein 1,8.0,False,CHEMBL3898,"[{'accession': 'P13497', 'component_descriptio...",SINGLE PROTEIN,9606.0
2,[],Rattus norvegicus,B2 bradykinin receptor,8.0,False,CHEMBL2501,"[{'accession': 'P25023', 'component_descriptio...",SINGLE PROTEIN,10116.0
3,[],Rattus norvegicus,B1 bradykinin receptor,8.0,False,CHEMBL4613,"[{'accession': 'P97583', 'component_descriptio...",SINGLE PROTEIN,10116.0
4,[],Homo sapiens,B1 bradykinin receptor,8.0,False,CHEMBL4308,"[{'accession': 'P46663', 'component_descriptio...",SINGLE PROTEIN,9606.0

**Reterive Bioactivity data for selected target**

In [8]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL3157'

**Now retrieve only bioactivity data for target; **GTPase NKX3-1(CHEMBL3157)** with reported IC 50  values in nM (nanomolar) unit.**

In [9]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [10]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,145803,[],CHEMBL653421,Concentration required to inhibit specific bin...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,43.0
1,None,None,145804,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,67.0
2,None,None,145806,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,11.0
3,None,None,145810,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,0.51
4,None,None,146991,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,2.8

In [13]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [15]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in foler "data"**

In [16]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [17]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 556
-rw------- 1 root root 569296 Jan 28 21:21 bioactivity_raw_data.csv

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,145803,[],CHEMBL653421,Concentration required to inhibit specific binding of [3H]BK (1.2 nM) to A-431 cells (human epidermoid carcinoma) which express Bradykinin receptor B2 by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(COc3cccc4c3nc(C)n4C)c2Cl)cc1,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '12.39', 'le': '0.25', 'lle': '2.45', 'sei': '6.98'}",CHEMBL288603,,CHEMBL288603,7.37,0,http://www.openphacts.org/units/Nanomolar,251357,=,1,1,=,,IC50,nM,,43.0,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,43.0
,,145804,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(COc3cccc4c3nc(C)n4C)c2Cl)cc1,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '12.07', 'le': '0.24', 'lle': '2.25', 'sei': '6.80'}",CHEMBL288603,,CHEMBL288603,7.17,0,http://www.openphacts.org/units/Nanomolar,251357,=,1,1,=,,IC50,nM,,67.0,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,67.0
,,145806,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/c4ccc(C(=O)Nc5ccccc5)cc4)c3Cl)c2n1,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '12.18', 'le': '0.24', 'lle': '0.49', 'sei': '7.91'}",CHEMBL133005,,CHEMBL133005,7.96,0,http://www.openphacts.org/units/Nanomolar,251376,=,1,1,=,,IC50,nM,,11.0,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,11.0
,,145810,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/c4ccc(/C=C/c5ccncc5)nc4)c3Cl)c2n1,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '14.55', 'le': '0.28', 'lle': '2.11', 'sei': '9.55'}",CHEMBL130436,,CHEMBL130436,9.29,0,http://www.openphacts.org/units/Nanomolar,251391,=,1,1,=,,IC50,nM,,0.51,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,0.51
,,146991,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/c4ccc(NC(=O)c5ccncc5)nc4)c3Cl)c2n1.Cl.Cl.Cl,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '13.05', 'le': '0.25', 'lle': '2.29', 'sei': '6.77'}",CHEMBL555202,,CHEMBL1195721,8.55,0,http://www.openphacts.org/units/Nanomolar,251392,=,1,1,=,,IC50,nM,,2.8,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,2.8
,,148210,[],CHEMBL653421,Concentration required to inhibit specific binding of [3H]BK (1.2 nM) to A-431 cells (human epidermoid carcinoma) which express Bradykinin receptor B2 by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(COc3cccn4c(Br)c(C)nc34)c2Cl)cc1.Cl,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '13.38', 'le': '0.29', 'lle': '3.38', 'sei': '8.40'}",CHEMBL538732,,CHEMBL1189415,8.82,1,http://www.openphacts.org/units/Nanomolar,251347,=,1,1,=,,IC50,nM,,1.5,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,1.5
,,148211,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(COc3cccn4c(Br)c(C)nc34)c2Cl)cc1.Cl,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '12.20', 'le': '0.27', 'lle': '2.61', 'sei': '7.66'}",CHEMBL538732,,CHEMBL1189415,8.05,0,http://www.openphacts.org/units/Nanomolar,251347,=,1,1,=,,IC50,nM,,9.0,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,9.0
,,148213,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1nc2c(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/c4ccc(C(=O)N(C)C)cc4)c3Cl)cccc2n1C,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '12.58', 'le': '0.25', 'lle': '2.89', 'sei': '7.41'}",CHEMBL132510,,CHEMBL132510,7.85,0,http://www.openphacts.org/units/Nanomolar,251371,=,1,1,=,,IC50,nM,,14.0,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,14.0
,,149347,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM) to human Bradykinin receptor B2 which was expressed in CHO (Chinese hamster ovary) cells by 50%.,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1nc2c(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/c4ccc(NC(C)=O)nc4)c3Cl)cccc2n1C,,,CHEMBL1131138,J Med Chem,1998.0,"{'bei': '13.70', 'le': '0.27', 'lle': '3.77', 'sei': '6.56'}",CHEMBL264751,,CHEMBL264751,8.38,0,http://www.openphacts.org/units/Nanomolar,251370,=,1,1,=,,IC50,nM,,4.2,CHEMBL3157,Homo sapiens,B2 bradykinin receptor,9606,,,IC50,nM,UO_0000065,,4.2

# **Step 3: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected KRAS target.**

**Inspect Missing Values**

In [20]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [21]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,145803,[],CHEMBL653421,Concentration required to inhibit specific bin...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,43.0
1,None,None,145804,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,67.0
2,None,None,145806,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,11.0
3,None,None,145810,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,0.51
4,None,None,146991,[],CHEMBL653418,Inhibition specific binding of [3H]BK (1.0 nM)...,B,None,None,BAO_0000190,...,Homo sapiens,B2 bradykinin receptor,9606,None,None,IC50,nM,UO_0000065,None,2.8

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [22]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [23]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [24]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
    bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [25]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL288603,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(C...,43.0,active
1,CHEMBL288603,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(C...,67.0,active
2,CHEMBL133005,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/...,11.0,active
3,CHEMBL130436,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/...,0.51,active
4,CHEMBL555202,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/...,2.8,active

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [26]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL288603,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(C...,43.0,active
1,CHEMBL288603,CNC(=O)c1ccc(/C=C/C(=O)NCC(=O)N(C)c2ccc(Cl)c(C...,67.0,active
2,CHEMBL133005,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/...,11.0,active
3,CHEMBL130436,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/...,0.51,active
4,CHEMBL555202,Cc1ccc2cccc(OCc3c(Cl)ccc(N(C)C(=O)CNC(=O)/C=C/...,2.8,active

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [30]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

cp: failed to access '/content/gdrive/My Drive/Colab Notebooks/data': Transport endpoint is not connected
ls: cannot access '/content/gdrive/My Drive/Colab Notebooks/data': Transport endpoint is not connected

## **End of Part 1: Data Collection and Curation**